import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the folder structure under docs/.
 * Category labels/order live in each folder's _category_.json,
 * and per-page order via the `sidebar_position` front matter.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
